paginate:
  per_page: 4
category:
  food: 1
  drink: 2
  name:
    maxium: 50
suggest:
  name:
    minimum: 8
admin:
  products:
    picture_width: 650
    picture_height: 650
    name:
      minimum: 8
product:
  minimum: 10000
  maximum: 100000
  paginate:
    per_page: 5
