paginate:
  per_page: 4
category:
  food: 1
  drink: 2
  name:
    maxium: 50
suggest:
  name:
    minimum: 8
  price:
    minimum: 10000
    maximum: 100000
admin:
  products:
    picture_width: 650
    picture_height: 650
    name:
      minimum: 8
product:
  minimum: 10000
  maximum: 100000
  paginate:
    per_page: 5
  price:
    minimum: 10000
    maximum: 100000
suggests:
  pending: 0
  accept_status: 1
  refuse_status: 2
  paginate:
    per_page: 7
orders:
  accept_status: 1
  refuse_status: 2
